### PR TITLE
rebase our jenkins-job-builder fork on latest upstream release

### PR DESCRIPTION
**Pull request by evgeni**
this rebases our fork on top of upstreams 2.0.2 release. the only tfm-specific addition is `schedule-failed-builds` (which we should get rid of eventually).

for comparison, we had the following commits in our fork:

```
commit 0ba5c0a1652363b12cd2eedf818beb882984b7ca
Author: Dominic Cleal <dominic@cleal.org>
Date:   Thu Aug 25 11:20:44 2016 +0100

    Add cancel-builds-on-update to GHPRB trigger
    
    Change-Id: I05c2643622f469d105d53751780b0445527faf0f
```

this was applied upstream in eb8a54fa45aa1f20aac1207972c0159bf3b09c1a and we don't have to carry it anymore

```
commit e29e7ec3a9dcec8a498c4edddda2f3c8475bcaf6
Author: Greg Sutcliffe <greg.Sutcliffe@gmail.com>
Date:   Thu Mar 12 16:25:58 2015 +0000

    Allow only-successful in artifact archiver
    
    Simple enough ;)
```

this is not needed anymore since theforeman/foreman-infra@1dd38357b751a67362131f7d67e1e5dee1ece061

```
commit d95d0ae5ede11a16591fcde02d2821ab3d2479ee
Author: Greg Sutcliffe <gsutclif@redhat.com>
Date:   Thu Mar 12 15:55:31 2015 +0000

    Support schedule-failed-builds plugin
```
that was ported to latest jjb by @GregSutcliffe and me, but (rightfully) rejected upstream in https://review.openstack.org/#/c/518739/

if you're insterested, https://gist.github.com/evgeni/7b84e956bb97da4c57ebd72f73d36401 has a diff between all our jobs generated by the old and new forks. does not look *too* scary.

### CODE REVIEW

**Comment by ekohl** [comment]
I don't mind this, but I wonder if we should replace that plugin and go straight to vanilla JJB.

**Comment by evgeni** [comment]
we should, but we'd still have to verify stuff works with 2.0.x, so we can also split the efforts and replace the old plugin in step2.

**Comment by evgeni** [comment]
I've opened https://github.com/theforeman/foreman-infra/issues/491 for the replacement.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-infra/pull/492 is the alternative PR, ripping out our fork completely.

**Comment by evgeni** [comment]
closing as https://github.com/theforeman/foreman-infra/pull/492 is merged now.

**Pull request closed without merging**
